name: petprep_hmc
channels:
  - apple
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - atk-1.0=2.38.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - ci-info=0.3.0
  - click=8.1.3
  - contourpy=1.0.7
  - cryptography=40.0.2
  - cycler=0.11.0
  - etelemetry=0.3.0
  - expat=2.5.0
  - filelock=3.11.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.3
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - gettext=0.21.1
  - giflib=5.2.1
  - graphite2=1.3.13
  - graphviz=7.1.0
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=6.0.0
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.4.1
  - importlib-resources=5.12.0
  - importlib_resources=5.12.0
  - isodate=0.6.1
  - kiwisolver=1.4.4
  - lcms2=2.15
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=16.0.1
  - libdeflate=1.18
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libglib=2.76.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - librsvg=2.54.4
  - libsqlite=3.40.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libwebp=1.3.0
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvm-openmp=16.0.1
  - looseversion=1.1.2
  - lxml=4.9.2
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - munkres=1.1.4
  - ncurses=6.3
  - networkx=3.1
  - nibabel=5.1.0
  - numpy=1.24.2
  - openjpeg=2.5.0
  - openssl=3.1.0
  - packaging=23.1
  - pandas=2.0.0
  - pango=1.50.14
  - patsy=0.5.3
  - pcre2=10.40
  - pillow=9.5.0
  - pip=23.1
  - pixman=0.40.0
  - platformdirs=3.2.0
  - pooch=1.7.0
  - prov=2.0.0
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pycparser=2.21
  - pydot=1.4.2
  - pyopenssl=23.1.1
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2023.3
  - rdflib=6.3.2
  - readline=8.2
  - requests=2.28.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - setuptools=67.6.1
  - simplejson=3.19.1
  - six=1.16.0
  - statsmodels=0.13.5
  - tk=8.6.12
  - tornado=6.2
  - traits=6.3.2
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wheel=0.40.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xvfbwrapper=0.2.9
  - xz=5.2.6
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - astor==0.8.1
    - bids==0.0
    - bids-validator==1.11.0
    - docopt==0.6.2
    - formulaic==0.5.2
    - interface-meta==1.3.0
    - num2words==0.5.12
    - pybids==0.15.6
    - sqlalchemy==1.3.24
    - wrapt==1.15.0
    - niworkflows==1.7.9
    - nipype==1.8.6
