name: petprep_hmc
channels:
  - apple
  - conda-forge
  - defaults
dependencies:
  - brotli=1.0.9=hb7f2c08_8
  - brotli-bin=1.0.9=hb7f2c08_8
  - brotlipy=0.7.0=py39ha30fb19_1005
  - bzip2=1.0.8=h0d85af4_4
  - ca-certificates=2022.12.7=h033912b_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39h131948b_3
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - contourpy=1.0.7=py39h92daf61_0
  - cryptography=40.0.2=py39hbeae22c_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - fonttools=4.39.3=py39ha30fb19_0
  - freetype=2.12.1=h3f81eb7_1
  - idna=3.4=pyhd8ed1ab_0
  - importlib-resources=5.12.0=pyhd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py39h92daf61_1
  - lcms2=2.15=h2dcdeff_1
  - lerc=4.0.0=hb486fe8_0
  - libblas=3.9.0=16_osx64_openblas
  - libbrotlicommon=1.0.9=hb7f2c08_8
  - libbrotlidec=1.0.9=hb7f2c08_8
  - libbrotlienc=1.0.9=hb7f2c08_8
  - libcblas=3.9.0=16_osx64_openblas
  - libcxx=16.0.1=h71dddab_0
  - libdeflate=1.18=hac1461d_0
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=11_3_0_h97931a8_31
  - libgfortran5=12.2.0=he409387_31
  - libjpeg-turbo=2.1.5.1=hb7f2c08_0
  - liblapack=3.9.0=16_osx64_openblas
  - libopenblas=0.3.21=openmp_h429af6e_3
  - libpng=1.6.39=ha978bb4_0
  - libsqlite=3.40.0=ha978bb4_0
  - libtiff=4.5.0=hedf67fa_6
  - libwebp-base=1.3.0=hb7f2c08_0
  - libxcb=1.13=h0d85af4_1004
  - libzlib=1.2.13=hfd90126_4
  - llvm-openmp=16.0.1=h61d9ccf_0
  - matplotlib=3.7.1=py39h6e9494a_0
  - matplotlib-base=3.7.1=py39hb2f573b_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=h96cf925_1
  - nibabel=5.1.0=py39h6e9494a_2
  - numpy=1.24.2=py39h6ee2318_0
  - openjpeg=2.5.0=h13ac156_2
  - openssl=3.1.0=hfd90126_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.0=py39hecff1ad_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pillow=9.5.0=py39h77c96bc_0
  - pip=23.1=pyhd8ed1ab_0
  - platformdirs=3.2.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - pthread-stubs=0.4=hc929b4f_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.16=h709bd14_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytz=2023.3=pyhd8ed1ab_0
  - readline=8.2=h9e318b2_1
  - requests=2.28.2=pyhd8ed1ab_1
  - scipy=1.10.1=py39h8a15683_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - setuptools=67.6.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - statsmodels=0.13.5=py39h7cc1f47_2
  - tk=8.6.12=h5dbffcc_0
  - tornado=6.2=py39ha30fb19_1
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - unicodedata2=15.0.0=py39ha30fb19_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h35c211d_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xz=5.2.6=h775f41a_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zstd=1.5.2=hbc0c0cd_6
prefix: /Users/martinnorgaard/opt/anaconda3/envs/petprep_hmc
